version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: ng-cash
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/data/postgresql
volumes:
  pgdata:
    driver: local
